USE PROJETO_FINANCEIRO; 
go
create or alter procedure sp_gerador_parcelas
    @ID_NF_ENTRADA int,
    @DATA_EMISSAO date,
    @VALOR_TOTAL decimal(16,2),
    @ID_CONDICAO int
as
begin
declare
    @DATA_VENCIMENTO date,
    @NUM_PARCELA int = 1,
    @VALOR_PARCELA decimal(16,2),
    @STATUS_PAGAMENTO bit = 0,
    @QTD_PARCELAS int,
    @ENTRADA bit

    select
        @ENTRADA = ENTRADA,
        @QTD_PARCELAS = QTD_PARCELAS
    from PROJETO_FINANCEIRO.DBO.CONDICAO_PAGAMENTO
    where ID_CONDICAO = @ID_CONDICAO

    while @NUM_PARCELA <= @QTD_PARCELAS
    begin

        set @VALOR_PARCELA = @VALOR_TOTAL/@QTD_PARCELAS;
        set @DATA_VENCIMENTO = dateadd(month,@NUM_PARCELA - @ENTRADA,@DATA_EMISSAO)
        insert into PROJETO_FINANCEIRO.DBO.PROGRAMACAO_PAGAMENTO
        (ID_NF_ENTRADA, DATA_VENCIMENTO, DATA_PGT_EFETUADO, NUM_PARCELA, VALOR_PARCELA, VALOR_PARCELA_PAGO, STATUS_PAGAMENTO)
        values (@ID_NF_ENTRADA, @DATA_VENCIMENTO, @DATA_VENCIMENTO, @NUM_PARCELA, @VALOR_PARCELA, @VALOR_PARCELA, @STATUS_PAGAMENTO)
        set @NUM_PARCELA = @NUM_PARCELA + 1;
    end;
end