USE PROJETO_FINANCEIRO; 
go
create or alter procedure sp_update_endereco_fornecedores as
    begin tran
		UPDATE PROJETO_FINANCEIRO.DBO.ENDERECOS_FORNECEDORES
		set
			ENDERECOS_FORNECEDORES.CEP = c.CEP,
			ENDERECOS_FORNECEDORES.COMPLEMENTO = c.COMPLEMENTO,
			ENDERECOS_FORNECEDORES.NUMERO = c.NUM_ENDERECO
		from PROJETO_FINANCEIRO.DBO.ENDERECOS_FORNECEDORES
		inner join PROJETO_FINANCEIRO.DBO.FORNECEDORES f
		on ENDERECOS_FORNECEDORES.ID_FORNECEDOR = f.ID_FORNECEDOR
		inner join STAGE.DBO.TRATAMENTO_COMPRAS_FINAL c
		on f.CNPJ_FORNECEDOR = c.CNPJ_FORNECEDOR
		where ENDERECOS_FORNECEDORES.CEP != c.CEP
		or ENDERECOS_FORNECEDORES.COMPLEMENTO != c.COMPLEMENTO
		or ENDERECOS_FORNECEDORES.NUMERO != c.NUM_ENDERECO
    commit