USE PROJETO_FINANCEIRO; 
go
create or alter procedure sp_update_programacao_pagamento as
    begin tran
		UPDATE PROJETO_FINANCEIRO.DBO.PROGRAMACAO_PAGAMENTO
		set
			PROGRAMACAO_PAGAMENTO.DATA_PGT_EFETUADO = E.DATA_PGT_EFETUADO,
			PROGRAMACAO_PAGAMENTO.VALOR_PARCELA_PAGO = E.VALOR_PARCELA_PAGO,
			PROGRAMACAO_PAGAMENTO.STATUS_PAGAMENTO = 1
		from PROJETO_FINANCEIRO.DBO.PROGRAMACAO_PAGAMENTO
		inner join STAGE.DBO.TRATAMENTO_PAGAMENTOS_EFETUADOS E on PROGRAMACAO_PAGAMENTO.ID_NF_ENTRADA = E.ID_NF_ENTRADA
		where PROGRAMACAO_PAGAMENTO.DATA_VENCIMENTO = E.DATA_VENCIMENTO and PROGRAMACAO_PAGAMENTO.STATUS_PAGAMENTO = 0
--INSERT DOS PAGAMENTOS EFETUADOS DA TABELA DE PROGRAMACAO NO HISTORICO
		insert into PROJETO_FINANCEIRO.DBO.HISTORICO_PAGAMENTO
		select
		pag.ID_PROG_PAGAMENTO,
		nf.ID_NF_ENTRADA,
		c.QTD_PARCELAS,
		pag.NUM_PARCELA,
		pag.DATA_VENCIMENTO,
		pag.DATA_PGT_EFETUADO,
		pag.VALOR_PARCELA,
		pag.VALOR_PARCELA_PAGO,
		(pag.VALOR_PARCELA - VALOR_PARCELA_PAGO)
		from PROJETO_FINANCEIRO.DBO.PROGRAMACAO_PAGAMENTO pag
		inner join PROJETO_FINANCEIRO.DBO.NOTAS_FISCAIS_ENTRADA nf
		on pag.ID_NF_ENTRADA = nf.ID_NF_ENTRADA
		inner join PROJETO_FINANCEIRO.DBO.CONDICAO_PAGAMENTO c
		on nf.ID_CONDICAO = c.ID_CONDICAO
		where pag.STATUS_PAGAMENTO = 1 and ID_PROG_PAGAMENTO not in (select ID_PROG_PAGAMENTO from PROJETO_FINANCEIRO.DBO.HISTORICO_PAGAMENTO)
	commit 