USE PROJETO_FINANCEIRO; 
go
create or alter procedure sp_update_fornecedores as
    begin tran
		UPDATE PROJETO_FINANCEIRO.DBO.FORNECEDORES
		set
			FORNECEDORES.NOME_FORNECEDOR = ATUAL.NOME_FORNECEDOR,
			FORNECEDORES.EMAIL_FORNECEDOR = ATUAL.EMAIL_FORNECEDOR,
			FORNECEDORES.TELEFONE_FORNECEDOR = ATUAL.TELEFONE_FORNECEDOR
		from PROJETO_FINANCEIRO.DBO.FORNECEDORES
		inner join STAGE.DBO.TRATAMENTO_COMPRAS_FINAL ATUAL on FORNECEDORES.CNPJ_FORNECEDOR = ATUAL.CNPJ_FORNECEDOR
		where FORNECEDORES.NOME_FORNECEDOR != ATUAL.NOME_FORNECEDOR
		or FORNECEDORES.EMAIL_FORNECEDOR != ATUAL.EMAIL_FORNECEDOR
		or FORNECEDORES.TELEFONE_FORNECEDOR != ATUAL.TELEFONE_FORNECEDOR;
    commit