use PROJETO_FINANCEIRO;
go
create or alter procedure sp_insert_recebimento as
begin
insert into PROJETO_FINANCEIRO.DBO.HISTORICO_RECEBIMENTO
(ID_PROG_RECEBIMENTO, ID_DESCONTO, DATA_RECEBIDO, VALOR_TOTAL_EM_HAVER, VALOR_PAGO)
SELECT 
	ID_PROG_RECEBIMENTO, 
	ID_DESCONTO, 
	DATA_RECEBIDO, 
	VALOR_TOTAL_EM_HAVER, 
	VALOR_PAGO
from STAGE.DBO.RECEBIMENTO_FINAL


update PROJETO_FINANCEIRO.DBO.PROGRAMACAO_RECEBIMENTO
set STATUS_RECEBIMENTO = 0
where ID_PROG_RECEBIMENTO in (select ID_PROG_RECEBIMENTO from PROJETO_FINANCEIRO.DBO.HISTORICO_RECEBIMENTO)

end;