use PROJETO_FINANCEIRO;
go
CREATE OR ALTER PROCEDURE sp_notas_fiscais_saida
AS
	BEGIN TRAN
	DECLARE insert_nota_fiscal CURSOR FOR
	SELECT 
		CLI.ID_CLIENTE,
		E2.ID_CONDICAO_PAGAMENTO,
		E2.NUMERO_NF,
		E2.DATA_EMISSAO,
		E2.VALOR_NET,
		E2.VALOR_TRIBUTO,
		E2.VALOR_TOTAL,
		E2.NOME_ITEM,
		E2.QTD_ITEM
	FROM STAGE.DBO.TRATAMENTO_VENDAS_FINAL E2
	JOIN PROJETO_FINANCEIRO.DBO.CLIENTES AS CLI ON CLI.CNPJ = E2.CNPJ_CLIENTE

	OPEN insert_nota_fiscal

	DECLARE
		@ID_CLIENTE INT,
		@ID_CONDICAO INT,
		@NUMERO_NF VARCHAR(100),
		@DATA_EMISSAO DATE,
		@VALOR_NET DECIMAL(20,2),
		@VALOR_TRIBUTO DECIMAL(20,2),
		@VALOR_TOTAL DECIMAL(20,2),
		@NOME_ITEM VARCHAR(100),
		@QTD_ITEM INT

	FETCH NEXT FROM insert_nota_fiscal INTO
		@ID_CLIENTE, 
		@ID_CONDICAO, 
		@NUMERO_NF,
		@DATA_EMISSAO,
		@VALOR_NET,
		@VALOR_TRIBUTO,
		@VALOR_TOTAL,
		@NOME_ITEM,
		@QTD_ITEM

	WHILE @@FETCH_STATUS = 0
	BEGIN
		BEGIN TRAN

			insert into 
			PROJETO_FINANCEIRO.DBO.NOTAS_FISCAIS_SAIDA
			(ID_CLIENTE, ID_CONDICAO, NUMERO_NF, DATA_EMISSAO, VALOR_NET, VALOR_TRIBUTO, VALOR_TOTAL, NOME_ITEM, QTD_ITEM)
			values
			(@ID_CLIENTE, @ID_CONDICAO, @NUMERO_NF,	@DATA_EMISSAO, @VALOR_NET, @VALOR_TRIBUTO, @VALOR_TOTAL, @NOME_ITEM, @QTD_ITEM)
		
			FETCH NEXT FROM insert_nota_fiscal INTO
			@ID_CLIENTE, 
			@ID_CONDICAO, 
			@NUMERO_NF,
			@DATA_EMISSAO,
			@VALOR_NET,
			@VALOR_TRIBUTO,
			@VALOR_TOTAL,
			@NOME_ITEM,
			@QTD_ITEM

		COMMIT 
	END
CLOSE insert_nota_fiscal
DEALLOCATE insert_nota_fiscal
COMMIT
