use PROJETO_FINANCEIRO;
go
CREATE OR ALTER PROCEDURE sp_gerar_parcelas_vendas
	@ID_NF_SAIDA int,
	@DATA_EMISSAO date,
	@VALOR_TOTAL decimal(16,2),
	@ID_CONDICAO int
AS
BEGIN
declare
	@DATA_VENCIMENTO date,
	@NUM_PARCELA int = 1,
	@VALOR_PARCELA decimal(16,2),
	@STATUS_RECEBIMENTO bit = 1,
	@QTD_PARCELAS int = 1,
	@ENTRADA bit

	SELECT 
		@ENTRADA = ENTRADA,
		@QTD_PARCELAS = QTD_PARCELAS
	FROM PROJETO_FINANCEIRO.DBO.CONDICAO_PAGAMENTO
	WHERE ID_CONDICAO = @ID_CONDICAO

	WHILE @NUM_PARCELA <= @QTD_PARCELAS
	BEGIN

	SET @VALOR_PARCELA = @VALOR_TOTAL / @QTD_PARCELAS;
	SET @DATA_VENCIMENTO = dateadd(month,@NUM_PARCELA -@ENTRADA, @DATA_EMISSAO)
		
	INSERT INTO PROJETO_FINANCEIRO.DBO.PROGRAMACAO_RECEBIMENTO
	(ID_NF_SAIDA, DATA_VENCIMENTO, NUM_PARCELA, VALOR_PARCELA, STATUS_RECEBIMENTO) 
	values (@ID_NF_SAIDA, @DATA_VENCIMENTO, @NUM_PARCELA, @VALOR_PARCELA, @STATUS_RECEBIMENTO)
	SET @NUM_PARCELA = @NUM_PARCELA + 1;
	END;
END;

GO

CREATE OR ALTER TRIGGER tr_gerar_parcelas_vendas
on PROJETO_FINANCEIRO.DBO.NOTAS_FISCAIS_SAIDA
AFTER INSERT
AS BEGIN

	DECLARE
	@ID_NF_SAIDA int,
	@DATA_EMISSAO date,
	@VALOR_TOTAL decimal(16,2),
	@ID_CONDICAO int

	SELECT
		@ID_NF_SAIDA = ID_NF_SAIDA,
		@DATA_EMISSAO = DATA_EMISSAO, 
		@VALOR_TOTAL = VALOR_TOTAL,
		@ID_CONDICAO = ID_CONDICAO
	FROM inserted

	EXEC sp_gerar_parcelas_vendas @ID_NF_SAIDA, @DATA_EMISSAO, @VALOR_TOTAL, @ID_CONDICAO
END