If(DB_ID(N'stage') IS NULL)
create database stage
go

use stage
If(OBJECT_ID(N'PAGAMENTOS_EFETUADOS') IS NULL)
CREATE TABLE [dbo].[PAGAMENTOS_EFETUADOS](
	[ID_NF_ENTRADA] [int] NULL,
	[DATA_VENCIMENTO] [date] NULL,
	[DATA_PGT_EFETUADO] [date] NULL,
	[VALOR_PARCELA_PAGO] [decimal](16, 2) NULL
);
go
If(OBJECT_ID(N'COMPRAS') IS NULL)
CREATE TABLE [dbo].[COMPRAS](
    [NOME_FORNECEDOR] [varchar](100) NULL,
    [CNPJ_FORNECEDOR] [varchar](100) NULL,
    [EMAIL_FORNECEDOR] [varchar](100) NULL,
    [TELEFONE_FORNECEDOR] [varchar](20) NULL,
    [NUMERO_NF] [varchar](100) NULL,
    [DATA_EMISSAO] [date] NULL,
    [VALOR_NET] [decimal](20, 2) NULL,
    [VALOR_TRIBUTO] [decimal](20, 2) NULL,
    [VALOR_TOTAL] [decimal](20, 2) NULL,
    [NOME_ITEM] [varchar](100) NULL,
    [QTD_ITEM] [int] NULL,
    [CONDICAO_PAGAMENTO] [varchar](100) NULL,
    [CEP] [int] NULL,
    [NUM_ENDERECO] [int] NULL,
    [COMPLEMENTO] [varchar](100) NULL,
    [TIPO_ENDERECO] [varchar](100) NULL,
    [DATA_PROCESSAMENTO] [date] NULL
);
go
If(OBJECT_ID(N'VALIDACAO_COMPRAS') IS NULL)
CREATE TABLE [dbo].[VALIDACAO_COMPRAS](
	[DATA_PROCESSAMENTO] [date] NULL,
	[DATA_EMISSAO] [date] NULL,
	[NUM_NF] [int] NULL,
	[CNPJ_FORNECEDOR] [VARCHAR](100) NULL
);
go
If(OBJECT_ID(N'VALIDACAO_COMPRAS_REJEITADOS') IS NULL)
CREATE TABLE [dbo].[VALIDACAO_COMPRAS_REJEITADOS](
	[NOME_FORNECEDOR] [varchar](100) NULL,
	[CNPJ_FORNECEDOR] [varchar](100) NULL,
	[EMAIL_FORNECEDOR] [varchar](100) NULL,
	[TELEFONE_FORNECEDOR] [varchar](20) NULL,
	[NUMERO_NF] [varchar](100) NULL,
	[DATA_EMISSAO] [date] NULL,
	[VALOR_NET] [decimal](20, 2) NULL,
	[VALOR_TRIBUTO] [decimal](20, 2) NULL,
	[VALOR_TOTAL] [decimal](20, 2) NULL,
	[NOME_ITEM] [varchar](100) NULL,
	[QTD_ITEM] [int] NULL,
	[ID_CONDICAO_PAGAMENTO] [varchar](100) NOT NULL,
	[CEP] [int] NULL,
	[NUM_ENDERECO] [int] NULL,
	[COMPLEMENTO] [varchar](100) NOT NULL,
	[TIPO_ENDERECO] [varchar](100) NULL,
	[DATA_PROCESSAMENTO] [date] NULL,
	[MOTIVO_DUPLICATAS] [varchar](200) NULL,
	[MOTIVO_NULLS] [varchar](200) NULL,
	[MOTIVO_CEP] [varchar](200) NULL
);
go
If(OBJECT_ID(N'PAGAMENTOS_EFETUADOS_REJEITADOS') IS NULL)
CREATE TABLE [dbo].[PAGAMENTOS_EFETUADOS_REJEITADOS](
	[ID_NF_ENTRADA] [int] NULL,
	[DATA_VENCIMENTO] [date] NULL,
	[DATA_PGT_EFETUADO] [date] NULL,
	[VALOR_PARCELA_PAGO] [decimal](16, 2) NULL,
	[MOTIVO_INEXISTENCIA] [varchar](200) NULL,
	[MOTIVO_NULL] [varchar](200) NULL
);
go
If(OBJECT_ID(N'VENDAS_REJEITADAS') IS NULL)
create table VENDAS_REJEITADAS(
NOME_CLIENTE varchar(100),
CNPJ_CLIENTE varchar(100),
EMAIL_CLIENTE varchar(100),
TELEFONE_CLIENTE varchar(20),
NUMERO_NF varchar(100),
DATA_EMISSAO date,
VALOR_NET decimal(20,2),
VALOR_TRIBUTO decimal(20,2),
VALOR_TOTAL decimal(20,2),
NOME_ITEM varchar(100),
QTD_ITEM int,
CONDICAO_PAGAMENTO varchar(100),
CEP int,
NUM_ENDERECO int,
COMPLEMENTO varchar(100),
TIPO_ENDERECO    varchar(100),
DATA_PROCESSAMENTO datetime
);
go
If(OBJECT_ID(N'VENDAS') IS NULL)
create table VENDAS(
NOME_CLIENTE varchar(100),
CNPJ_CLIENTE varchar(100),
EMAIL_CLIENTE varchar(100),
TELEFONE_CLIENTE varchar(20),
NUMERO_NF varchar(100),
DATA_EMISSAO date,
VALOR_NET decimal(20,2),
VALOR_TRIBUTO decimal(20,2),
VALOR_TOTAL decimal(20,2),
NOME_ITEM varchar(100),
QTD_ITEM int,
CONDICAO_PAGAMENTO varchar(100),
CEP int,
NUM_ENDERECO int,
COMPLEMENTO varchar(100),
TIPO_ENDERECO    varchar(100),
DATA_PROCESSAMENTO datetime
)
go
If(OBJECT_ID(N'VALIDACAO_VENDAS') IS NULL)
create table VALIDACAO_VENDAS (
DATA_PROCESSAMENTO datetime,
NUMERO_NF varchar(100),
DATA_EMISSAO date);

go
If(OBJECT_ID(N'VALIDACAO_VENDAS_REJEITADOS') IS NULL)
create table VALIDACAO_VENDAS_REJEITADOS(
NOME_CLIENTE varchar(100),
CNPJ_CLIENTE varchar(100),
EMAIL_CLIENTE varchar(100),
TELEFONE_CLIENTE varchar(20),
NUMERO_NF varchar(100),
DATA_EMISSAO date,
VALOR_NET decimal(20,2),
VALOR_TRIBUTO decimal(20,2),
VALOR_TOTAL decimal(20,2),
NOME_ITEM varchar(100),
QTD_ITEM int,
CONDICAO_PAGAMENTO varchar(100),
CEP int,
NUM_ENDERECO int,
COMPLEMENTO varchar(100),
TIPO_ENDERECO    varchar(100),
DATA_PROCESSAMENTO datetime
);
go
If(OBJECT_ID(N'CEP') IS NULL)
CREATE TABLE [dbo].[CEP](
    [CEP] [nvarchar](20) NULL,
    [UF_ENDERECO] [nvarchar](100) NULL,
    [CIDADE_ENDERECO] [nvarchar](200) NULL,
    [BAIRRO_ENDERECO] [nvarchar](200) NULL,
    [NOME_ENDERECO] [nvarchar](200) NULL
)
go
If(OBJECT_ID(N'RECEBIMENTO_REJEITADO') IS NULL)
CREATE TABLE [dbo].[RECEBIMENTO_REJEITADO](
    [NUMERO_NF] [int] NULL,
    [VALOR_RECEBIDO] [decimal](16, 2) NULL,
    [DATA_VENCIMENTO] [date] NULL,
    [DATA_RECEBIMENTO] [date] NOT NULL,
    [DATA_PROCESSAMENTO] [datetime] NULL
)
go
If(OBJECT_ID(N'RECEBIMENTO') IS NULL)
CREATE TABLE [dbo].[RECEBIMENTO](
    [NUMERO_NF] [int] NULL,
    [VALOR_RECEBIDO] [decimal](20, 2) NULL,
    [DATA_VENCIMENTO] [date] NULL,
    [DATA_RECEBIMENTO] [date] NULL,
    [DATA_PROCESSAMENTO] [date] NULL
) 
go
If(OBJECT_ID(N'RECEBIMENTO_FINAL') IS NULL)
CREATE TABLE [dbo].[RECEBIMENTO_FINAL](
   ID_PROG_RECEBIMENTO  int,
   ID_DESCONTO          int,
   DATA_RECEBIDO        date,
   VALOR_TOTAL_EM_HAVER decimal(16,2),
   VALOR_PAGO           decimal(16,2),
   MOTIVO VARCHAR(80)
)
GO
If(OBJECT_ID(N'EVIDENCIAS_FULL') IS NULL)
CREATE TABLE [dbo].[EVIDENCIAS_FULL] (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(255) NOT NULL,
    OBJETO NVARCHAR(50) NOT NULL,
    BANCO NVARCHAR(50) NOT NULL,
    STATUS_CRIACAO NVARCHAR(10) NOT NULL,
    DATA_CRIACAO NVARCHAR(255) NOT NULL,
    NUM_LINHA NVARCHAR(50) NOT NULL
);
